import type { Metadata } from "next"
import type { PropsWithChildren } from "react"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="en">
    <body>
      <main className="root">{children}</main>
    </body>
  </html>
)

export default RootLayout
