import type { Metadata } from "next"
import { NextIntlClientProvider } from "next-intl"
import type { PropsWithChildren } from "react"
import { Toaster } from "sonner"

import Header from "@/components/header"
import Providers from "@/components/providers"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="en">
    <body className="flex min-h-dvh flex-col">
      <Toaster />
      <Providers>
        <NextIntlClientProvider>
          <Header />
          <main className="root flex grow p-4">{children}</main>
        </NextIntlClientProvider>
      </Providers>
    </body>
  </html>
)

export default RootLayout
